/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2026-01-22 15:03:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Admin Home</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	  <div class=\"menubar secondnav \" style=\"background-color:white;\">\n");
      out.write("    <div id=\"menucontent\" class=\"container secondnav\">\n");
      out.write("      <div id=\"collapsable-nav\" class=\"collapse navbar-collapse hidden-lg hidden-md\">\n");
      out.write("        <ul id=\"nav-list\" class=\"nav navbar-nav navbar-left pull-left\">\n");
      out.write("            <li id=\"navHomeButton\">\n");
      out.write("              <a href=\"adminHome.jsp\">\n");
      out.write("                <span class=\"glyphicon glyphicon-home\"></span> Home</a> <!--Home button is here -->\n");
      out.write("            </li>\n");
      out.write("            <!-- <li class=\"dropdown\">\n");
      out.write("                <a class=\"dropdown-toggle \" data-toggle=\"dropdown\" data-animations=\"fadeIn fadeInLeft fadeInUp fadeInRight\" data-hover=\"dropdown\">Vendors\n");
      out.write("                    <span class=\"caret\"></span></a>    Dropdown under about us category\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"viewVendor.jsp\">View All Vendors</a></li>\n");
      out.write("                  <li><a href=\"ApproveVendor\">Approve Vendors</a></li>\n");
      out.write("                  <li><a href=\"vendorDetail.jsp\">Vendor Detail</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li> -->\n");
      out.write("              <li><a href=\"adminViewVendor.jsp\">Vendors</a></li>\n");
      out.write("              <li class=\"dropdown\">\n");
      out.write("                <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-animations=\"fadeIn fadeInLeft fadeInUp fadeInRight\"> \n");
      out.write("                <!--Dropdown under tender category -->\n");
      out.write("                  Tender\n");
      out.write("                    <span class=\"caret\"></span></a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"viewTender.jsp\">View all Tenders</a></li>\n");
      out.write("                  <li><a href=\"createTender.jsp\">Create New Tender</a></li>\n");
      out.write("                  <li><a href=\"viewTenderBids.jsp\">View Tender Bids</a></li>\n");
      out.write("                  <li><a href=\"viewTenderBids.jsp\">Accept a bid</a></li>\n");
      out.write("                  <li><a href=\"viewAssignedTenders.jsp\">View Assigned Tenders</a></li>\n");
      out.write("                  </ul>\n");
      out.write("             </li>\n");
      out.write("             \n");
      out.write("            <li class=\"dropdown\">\n");
      out.write("                <a class=\"dropdown-toggle \" data-toggle=\"dropdown\" data-animations=\"fadeIn fadeInLeft fadeInUp fadeInRight\" data-hover=\"dropdown\">Notice\n");
      out.write("                    <span class=\"caret\"></span></a>    <!--Dropdown under about us category -->\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"addNotice.jsp\">Add Notice</a></li>\n");
      out.write("                  <li><a href=\"removeNotice.jsp\">Remove Notice</a></li>\n");
      out.write("                  <li><a href=\"updateNotice.jsp\">Update Notice</a></li>\n");
      out.write("                  <li><a href=\"viewNotice.jsp\">View All Notice</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("               <li><a href=\"payment.jsp\" target=\"_self\">Payment</a></li>\n");
      out.write("\n");
      out.write("              \n");
      out.write("             <li>\n");
      out.write("            	<a href=\"LogoutSrv\">Logout</a>\n");
      out.write("        \n");
      out.write("            </li>\n");
      out.write("            \n");
      out.write("            <li>\n");
      out.write("              <!-- Form for searching any tenders or items-->\n");
      out.write("              <form class=\"navbar-form hidden-xs\" action=\"searchTender.jsp\"  >\n");
      out.write("                <div class=\"form-group\" >\n");
      out.write("                  <input type=\"text\" name=\"tid\" class=\"form-control\" placeholder=\"Find Tenders by name or tenderId\" style=\"margin-left:10px;\" required>\n");
      out.write("                </div>\n");
      out.write("               \n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\" >Search</button>\n");
      out.write("                \n");
      out.write("              </form>\n");
      out.write("              <!--End of form section-->\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
